spring:
  datasource:
    url: jdbc:h2:~/IdeaProjects/edu/CodeKata/maven-to-gradle/db/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true